services:
  tts:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "ENGINE_NAME=${ENGINE_NAME}"
        - "BASE_IMAGE=${BASE_IMAGE}"
    image: orion-tts:local
    pull_policy: build
    container_name: ${TTS_HOST}
    ports:
      - "${TTS_PORT}:${TTS_CONTAINER_PORT}"
    env_file:
      - ../.env.global
      - .env
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      - ./models:/app/models
      - ./voices:/app/voices
    networks:
      - orion-network
    restart: unless-stopped

networks:
  orion-network:
    external: true
    name: ${ORION_NETWORK}
