[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "orion-tts"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "python-multipart",
    "aiohttp",
    "numpy",
    "python-dotenv",
]

[tool.setuptools]
py-modules = []
packages = []
